### ISSUE TITLE
SGCN

### ISSUE THREAD

**Issue by libuyan-nuaa** [ZJU-DAILY/SGDL#5]
Do you implement the code of SGCN yourself, Could you please offer the code about SGCN?

**Comment by Scottdyt** [comment]
Hi,

Thanks for your interest about our paper. I contacted with the authors and implemented it myself to conduct the experiments in our paper. I am glad to share the code when I finishe refactoring the baselines. But it may takes a while.

However, there are some links that are useful to implement the SGCN. And you can also directly contact the authors for the original code.

[https://github.com/kuandeng/LightGCN](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkuandeng%2FLightGCN&data=04%7C01%7Chchen%40visa.com%7C2b76f3e589694690e93508d975db9a76%7C38305e12e15d4ee888b9c4db1c477d76%7C0%7C0%7C637670408332805075%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jkNQzM63CYnA8H6pDN3kn3VtKiTRJLDKgXojkDJ9URw%3D&reserved=0)
https://github.com/mingzhang-yin/ARM-gradient
https://github.com/cvlab-epfl/Power-Iteration-SVD

Hope it helps. Cheers :)
